version: '3.9'
name: vacation-planner
services:
  app:
    build:
      context: ../../source
      dockerfile: Dockerfile
    container_name: "vp-app"
    volumes:
      - ../../source/vpcoreproject/:/app/
      - static:/app/static
      - media:/app/media/
    environment:
      - DJANGO_SETTINGS_MODULE=vpcoreproject.settings
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - HOST_NAME=http://localhost:8000
      - DB_ENGINE=django.db.backends.postgresql_psycopg2
      - DB_HOST=vp-db
      - DB_DB=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=5432
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 manage.py collectstatic --noinput
        python3 manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: curl --fail http://0.0.0.0:8000/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network_back

  db:
    image: postgres:13
    container_name: "vp-db"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d postgres
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - core-postgres-vol:/var/lib/postgresql/data/:Z
    networks:
      - network_back

  nginx:
    build:
      context: ../../nginx/local
      dockerfile: Dockerfile
    environment:
      - APP_HOST_NAME=vp-app
      - APP_PORT=8000
    volumes:
      - static:/home/app/web/staticfiles
      - media:/home/app/web/mediafiles
    ports:
      - "8001:80"
    networks:
      - network_front
      - network_back
    depends_on:
      - app

networks:
  network_front:
    driver: bridge
    name: core_network_front
  network_back:
    driver: bridge
    internal: true
    name: core_network_back

volumes:
  static:
  media:
  core-postgres-vol:
