services:
  core:
    build:
      context: ../../source
      dockerfile: Dockerfile
    container_name: ${CORE_NAME}
    environment:
      - DJANGO_SETTINGS_MODULE=vpcoreproject.settings
      - ALLOWED_HOSTS=${CORE_ALLOWED_HOSTS}
      - CORE_HOST_NAME=${CORE_NAME}
      - CORE_PORT=${CORE_PORT}
      - DB_ENGINE=${CORE_DB_ENGINE}
      - DB_HOST=${CORE_DB_NAME}
      - DB_DB=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${POSTGRES_PORT}
      - SCRAPPER_HOST=scrapper
      - SCRAPPER_PORT=8002
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 manage.py runserver 0.0.0.0:${CORE_PORT}
    volumes:
      - ../../source/vpcoreproject/:/app/
    healthcheck:
      test: curl --fail http://0.0.0.0:${CORE_PORT}/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    depends_on:
      core-db:
        condition: service_healthy
    networks:
      - network_back
      - network_scrapper

  core-db:
    image: postgres:13
    container_name: ${CORE_DB_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./core-db/:/var/lib/postgresql/data/
    networks:
      - network_back

  nginx:
    build:
      context: ../../nginx/local
      dockerfile: Dockerfile
    environment:
      - CORE_HOST_NAME=${CORE_NAME}
      - CORE_PORT=${CORE_PORT}
    ports:
      - "8001:80"
    networks:
      - network_front
      - network_back
    depends_on:
      - core

networks:
  network_front:
    driver: bridge
    name: core_network_front
  network_back:
    driver: bridge
    internal: true
    name: core_network_back
  network_scrapper:
    name: scrapper_network_front
    external: True
