# Generated by Django 4.1.3 on 2023-04-03 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("places", "0003_place_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceScrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=40)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "PENDING"), (3, "SUCCESS"), (4, "FAILURE")],
                        default=0,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
