# Generated by Django 4.1.3 on 2023-01-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_alter_event_promoter"),
        ("friends", "0001_initial"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventchat",
            name="chat",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="chat.chat"
            ),
        ),
        migrations.AlterField(
            model_name="eventchat",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="events.event"
            ),
        ),
        migrations.AlterField(
            model_name="friendschat",
            name="chat",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="chat.chat"
            ),
        ),
        migrations.AlterField(
            model_name="friendschat",
            name="friends",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="friends.friends"
            ),
        ),
    ]
